import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
const source = readFileSync(process.argv[2], 'utf8').replace(/^import .*$/gm, '').replace(/export /g, '');
const data = new Map([['hermes.desktop.pluginDecisions.v2', JSON.stringify({'hermes-bots': true, 'bots-mod': false, other: false})]]);
const ctx = vm.createContext({window: {localStorage: {getItem: k => data.get(k), setItem: (k,v) => data.set(k,v)}}, atom: value => ({get: () => value, set: v => {value = v;}})});
vm.runInContext(stripTypeScriptTypes(source), ctx);
assert.equal(ctx.pluginActive('hermes-bots'), false);
assert.equal(ctx.pluginActive('bots-mod', false), true);
assert.equal(ctx.pluginActive('other'), false);
assert.equal(ctx.pluginActive('unknown'), true);
assert.equal(ctx.pluginActive('unknown', false), false);
await ctx.setPluginEnabled('hermes-bots', true);
await ctx.setPluginEnabled('bots-mod', false);
await ctx.setPluginEnabled('other', true);
assert.equal(ctx.pluginActive('hermes-bots'), false);
assert.equal(ctx.pluginActive('bots-mod'), true);
assert.equal(ctx.pluginActive('other'), true);
const saved = JSON.parse(data.get('hermes.desktop.pluginDecisions.v2'));
assert.equal(saved['hermes-bots'], false);
assert.equal(saved['bots-mod'], true);
console.log('PASS: managed choices override defaults, persisted decisions and toggles; other choices preserved');
