_: {
  finix.persistence.allowlist = {
    hideMounts = true;
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      {
        directory = "/root";
        mode = "0700";
      }
      "/var/lib/NetworkManager"
      "/var/lib/bluetooth"
      "/var/lib/btrbk"
      "/var/lib/manzil"
      "/var/lib/nixos"
      "/var/lib/sbctl"
      "/var/lib/systemd/coredump"
      "/var/lib/tailscale"
      "/var/log"
    ];
    files = ["/etc/machine-id"];
    users.y0usaf = {
      directories = [
        ".SteamCloud"
        ".azure"
        ".barony"
        ".cache/nix"
        ".cache/nv"
        ".config/AionUi"
        ".config/Cemu"
        ".config/Frame"
        ".config/GitHub Desktop"
        ".config/Hermes"
        ".config/age"
        ".config/agent-harness"
        ".config/bolt-launcher"
        ".config/camset"
        ".config/claude"
        ".config/dconf"
        ".config/epy"
        ".config/firefox"
        ".config/herdr"
        ".config/intent"
        ".config/manicode"
        ".config/nix"
        ".config/slskd"
        ".config/snowflake"
        ".config/unity3d"
        ".cookunity"
        ".cursor/sand"
        ".cursor/sand-dev"
        ".hermes"
        ".local/share/.Wurst encryption"
        ".local/share/.renpy"
        ".local/share/Baba_Is_You"
        ".local/share/Brotato"
        ".local/share/CassetteBeasts"
        ".local/share/Celeste"
        ".local/share/Cemu"
        ".local/share/HallsOfTorment"
        ".local/share/Noobs Are Coming (Save)"
        ".local/share/PrismLauncher"
        ".local/share/Rocket League"
        ".local/share/Smart Code ltd"
        ".local/share/SteamWorld Heist"
        ".local/share/Ultrapool"
        ".local/share/Vial"
        ".local/share/YourOnlyMoveIsHUSTLE"
        ".local/share/app.codeg"
        ".local/share/aspyr-media"
        ".local/share/balatroai"
        ".local/share/binding of isaac rebirth"
        ".local/share/bolt-launcher"
        ".local/share/com.jean.desktop"
        ".local/share/com.overboy.noobsarecoming"
        ".local/share/com.panes.app"
        ".local/share/dolphin-emu"
        ".local/share/gnupg"
        ".local/share/godot/app_userdata"
        ".local/share/hackerpg"
        ".local/share/keyrings"
        ".local/share/lootplot"
        ".local/share/mcp-trader"
        ".local/share/music-get"
        ".local/share/osu"
        ".local/share/pki"
        ".local/share/polybot"
        ".local/share/shapez.io"
        ".local/share/shipofharkinian"
        ".local/share/skua-wine"
        ".local/share/slskd"
        ".local/share/superfile"
        ".local/share/vibe-kanban"
        ".local/share/wine"
        ".local/state/bash"
        ".local/state/music-get"
        ".local/state/nix"
        ".local/state/superfile"
        ".mcp-auth"
        ".n8n-mcp"
        ".paseo"
        ".pki"
        ".slskd"
        ".steam"
        ".supabase"
        "Desktop"
        "Documents"
        "Downloads"
        "Games"
        "Tokens"
        "Videos"
        "cu-workbench"
        "finix"
        "inscend"
      ];
      files = [
        ".SNOW"
      ];
    };
  };
}
