(in-package #:tomoe-user)

(defun %policy-exclusive-edge (anchors)
  (flet ((exactly (&rest edges)
           (and (= (length anchors) (length edges))
                (every (lambda (edge) (member edge anchors)) edges))))
    (cond ((or (exactly :top) (exactly :top :left :right)) :top)
          ((or (exactly :bottom) (exactly :bottom :left :right)) :bottom)
          ((or (exactly :left) (exactly :left :top :bottom)) :left)
          ((or (exactly :right) (exactly :right :top :bottom)) :right))))

(defun %policy-insets (layers)
  (let ((top 0) (right 0) (bottom 0) (left 0))
    (dolist (layer layers)
      (let ((zone (getf layer :exclusive-zone))
            (margin (getf layer :margin)))
        (when (and (getf layer :visible) (integerp zone) (plusp zone))
          (let* ((edge (%policy-exclusive-edge (getf layer :anchors)))
                 (offset (case edge (:top (first margin)) (:right (second margin))
                                 (:bottom (third margin)) (:left (fourth margin))))
                 (inset (+ zone (or offset 0))))
            (when (plusp inset)
              (case edge
                (:top (setf top (max top inset)))
                (:right (setf right (max right inset)))
                (:bottom (setf bottom (max bottom inset)))
                (:left (setf left (max left inset)))))))))
    (list :top top :right right :bottom bottom :left left)))

(defun %usable-area (snapshot)
  "The first output, minus the exclusive zones of the visible layer surfaces."
  (let ((output (first (context snapshot :outputs))))
    (when output
      (let* ((insets (%policy-insets (context snapshot :layers)))
             (left (getf insets :left)) (top (getf insets :top)))
        (list :x (+ (getf output :x) left)
              :y (+ (getf output :y) top)
              :width (max 1 (- (getf output :width) left (getf insets :right)))
              :height (max 1 (- (getf output :height) top (getf insets :bottom))))))))

(defun %centred-box (area width height)
  "AREA comes from %usable-area; WIDTH and HEIGHT are pixels."
  (list (+ (getf area :x) (floor (- (getf area :width) width) 2))
        (+ (getf area :y) (floor (- (getf area :height) height) 2))
        width height))

(define-extension "displays" () (snapshot state event)
  (declare (ignore snapshot state event))
  (values nil
          (mapcar (lambda (output)
                    (apply #'configure-output (first output) (second output)))
                  +policy-displays+)
          nil))

(load (namestring (merge-pathnames +policy-deck-path+
                                   (user-homedir-pathname))))

(define-extension "floating" (:reads (:windows :outputs :layers :key :focus) :state nil)
    (snapshot floating event)
  (let* ((windows (context snapshot :windows))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (focused (context snapshot :focus))
         (window (find focused windows :key (lambda (w) (getf w :id))))
         (command (when (and (eq (getf event :type) :key)
                             (equal (getf event :owner) "floating"))
                    (getf event :command)))
         (area (%usable-area snapshot)))
    (setf floating (remove-if-not (lambda (entry) (member (car entry) ids)) floating))
    (when (and (equal command "toggle") window)
      (let ((id (getf window :id)))
        (cond
          ((getf window :fullscreen) nil)
          ((assoc id floating)
           (setf floating (remove id floating :key #'car)))
          (area
           (let ((width (max 1 (floor (* (getf area :width) +policy-floating-ratio+))))
                 (height (max 1 (floor (* (getf area :height) +policy-floating-ratio+)))))
             (setf floating (cons (cons id (%centred-box area width height)) floating)))))))
    (values floating
            (append (list (apply #'bind-key +policy-floating-binding+))
                    (when (and (equal command "toggle") window (getf window :fullscreen))
                      (list (fullscreen (getf window :id) nil)))
                    (loop for (id . box) in floating
                          collect (place id (first box) (second box)
                                         (third box) (fourth box) t)))
            nil)))

(define-extension "launcher" (:reads (:windows :outputs :layers :focus) :state nil)
    (snapshot previous event)
  (let* ((windows (context snapshot :windows))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (launchers (remove-if-not (lambda (window)
                                     (equal (getf window :app-id)
                                            (getf +policy-launcher+ :app-id)))
                                   windows))
         (launcher-ids (mapcar (lambda (window) (getf window :id)) launchers))
         (focused (context snapshot :focus))
         (type (getf event :type))
         (id (getf event :id))
         (area (%usable-area snapshot)))
    (when (and (eq type :map) (member id launcher-ids)) (setf previous focused))
    (let ((return-to (when (and (eq type :unmap) previous (member previous ids)
                                (null launcher-ids))
                       previous)))
      (values (if return-to nil previous)
              (append
               (when area
                 (let* ((ratio (getf +policy-launcher+ :ratio))
                        (width (max 1 (floor (* (getf area :width) ratio))))
                        (height (max 1 (floor (* (getf area :height) ratio)))))
                   (loop for window in launchers
                         for box = (%centred-box area width height)
                         collect (place (getf window :id) (first box) (second box)
                                        (third box) (fourth box) t))))
               (when return-to (list (focus return-to))))
              nil))))

(define-extension "rules" (:reads (:windows :focus) :state nil)
    (snapshot previous event)
  (let* ((windows (context snapshot :windows))
         (app-id (getf +policy-hidden-window+ :app-id))
         (prefix (getf +policy-hidden-window+ :title-prefix))
         (prefix-length (length prefix))
         (matched (remove-if-not
                   (lambda (window)
                     (and (equal (getf window :app-id) app-id)
                          (let ((title (getf window :title)))
                            (and title (>= (length title) prefix-length)
                                 (string= prefix title :end2 prefix-length)))))
                   windows))
         (matched-ids (mapcar (lambda (window) (getf window :id)) matched))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (focused (context snapshot :focus))
         (type (getf event :type))
         (id (getf event :id)))
    (when (and (eq type :map) (member id matched-ids)) (setf previous focused))
    (let ((target
           (when (and (eq type :map) (member id matched-ids))
             (or (and previous (member previous ids)
                      (not (member previous matched-ids))
                      previous)
                 (getf (find-if-not (lambda (window)
                                      (member (getf window :id) matched-ids))
                                    windows)
                       :id)))))
      (values previous
              (append (loop for window in matched
                            collect (place (getf window :id) 0 0 1 1 nil))
                      (when (and (eq type :map) (member id matched-ids))
                        (list (focus target))))
              nil))))

(define-extension "user" (:reads (:key :focus) :state nil) (snapshot state event)
  (declare (ignore state))
  (let ((command (when (and (eq (getf event :type) :key)
                            (equal (getf event :owner) "user"))
                   (getf event :command)))
        (focused (context snapshot :focus)))
    (values nil
            (mapcar (lambda (binding) (apply #'bind-key binding)) +policy-bindings+)
            (cond
              ((null command) nil)
              ((equal command "close") (when focused (list (close-window focused))))
              ((equal command "quit") (list (quit)))
              (t
               (let ((argv (second (assoc command +policy-launches+ :test #'equal))))
                 (when argv (list (apply #'launch argv)))))))))
