_: {
  finix.persistence.allowlist = {
    hideMounts = true;
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      "/var/lib/NetworkManager"
      "/var/lib/bluetooth"
      "/var/lib/docker"
      "/var/lib/manzil"
      "/var/lib/nixos"
      "/var/lib/systemd/coredump"
      "/var/lib/tailscale"
      "/var/log"
    ];
    files = ["/etc/machine-id"];
    users.y0usaf = {
      directories = [
        ".cache/ekko"
        ".cache/librewolf"
        ".cache/mesa_shader_cache"
        ".cache/nv"
        ".cache/wallust"
        ".config/Codex"
        ".config/Mullvad VPN"
        ".config/Pinta"
        ".config/Slack"
        ".config/Vencord"
        ".config/bolt-launcher"
        ".config/chromium"
        ".config/claude"
        ".config/codex"
        ".config/dconf"
        ".config/discord"
        ".config/discordcanary"
        ".config/ekko"
        ".config/gh"
        ".config/glide"
        ".config/gws"
        ".config/librewolf"
        ".config/nix"
        ".config/nushell"
        ".config/obsidian"
        ".config/opencode"
        ".config/pi-harness"
        ".config/pi/agent"
        ".config/syncthing"
        ".config/unity3d"
        ".config/vesktop"
        ".fx"
        ".librewolf"
        ".local/share/PrismLauncher"
        ".local/share/android"
        ".local/share/applications"
        ".local/share/azure"
        ".local/share/bun"
        ".local/share/cargo"
        ".local/share/com.pais.handy"
        ".local/share/com.vercel.cli"
        ".local/share/handy"
        ".local/share/icons"
        ".local/share/nvim"
        ".local/share/pi"
        ".local/share/pki"
        ".local/share/rtk"
        ".local/share/rustup"
        ".local/share/stremio"
        ".local/state/bash"
        ".local/state/codex"
        ".local/state/manzil"
        ".local/state/nix"
        ".local/state/nvim"
        ".local/state/pi-harness"
        ".local/state/wireplumber"
        ".mozilla"
        ".omfx"
        ".omp"
        ".ssh"
        ".steam"
        "Documents"
        "Tokens"
        "cu-workbench"
        "finix"
      ];
      files = [".npmrc"];
    };
  };
}
