(in-package #:tomoe-user)

(defun sway--leaves (tree)
  (cond ((null tree) nil)
        ((integerp tree) (list tree))
        (t (loop for kid in (rest tree) append (sway--leaves kid)))))

(defun sway--prune (tree keep)
  (cond ((null tree) nil)
        ((integerp tree) (when (member tree keep) tree))
        (t (let ((kids (loop for kid in (rest tree)
                             for pruned = (sway--prune kid keep)
                             when pruned collect pruned)))
             (if (rest kids) (cons (first tree) kids) (first kids))))))

(defun sway--insert (tree target id direction)
  (cond ((integerp tree) (if (eql tree target) (list direction tree id) tree))
        ((and (eq (first tree) direction) (member target (rest tree)))
         (let ((tail (member target (rest tree))))
           (append (ldiff tree (rest tail)) (list id) (rest tail))))
        (t (cons (first tree)
                 (loop for kid in (rest tree)
                       collect (if (member target (sway--leaves kid))
                                   (sway--insert kid target id direction)
                                   kid))))))

(defun sway--swap (tree a b)
  (cond ((eql tree a) b)
        ((eql tree b) a)
        ((atom tree) tree)
        (t (cons (first tree) (loop for kid in (rest tree) collect (sway--swap kid a b))))))

(defun sway--boxes (tree x y width height gap)
  (if (integerp tree)
      (list (list tree x y width height))
      (let* ((kids (rest tree))
             (horizontal (eq (first tree) :h))
             (origin (if horizontal x y))
             (span (if horizontal width height))
             (step (floor (- span (* (1- (length kids)) gap)) (length kids)))
             (start origin))
        (loop for (kid . more) on kids
              for size = (if more step (- (+ origin span) start))
              append (if horizontal
                         (sway--boxes kid start y size height gap)
                         (sway--boxes kid x start width size gap))
              do (incf start (+ size gap))))))

(defun sway--neighbour (boxes id dx dy)
  (let ((from (assoc id boxes)) (best nil) (distance nil))
    (flet ((centre (box) (list (+ (second box) (/ (fourth box) 2)) (+ (third box) (/ (fifth box) 2)))))
      (when from
        (destructuring-bind (fx fy) (centre from)
          (dolist (box boxes)
            (destructuring-bind (cx cy) (centre box)
              (let* ((ddx (- cx fx)) (ddy (- cy fy))
                     (along (if (zerop dx) ddy ddx))
                     (across (if (zerop dx) ddx ddy))
                     (far (+ (abs ddx) (abs ddy))))
                (when (and (not (eq box from))
                           (eq (plusp along) (plusp (+ dx dy)))
                           (> (abs along) (abs across))
                           (or (null distance) (< far distance)))
                  (setf best (first box) distance far))))))))
    best))

(define-extension "sway"
    (:reads (:windows :rules :workareas :outputs :focus :key :button :request)
     :state (list :active 1 :workspaces nil :trees nil :split nil :focus nil
                  :fullscreen nil :floating nil)
     :admission t)
    (snapshot state event)
  (let* ((windows (remove-if (lambda (window) (policy--unmanaged-p snapshot window))
                             (context snapshot :windows)))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (count (getf +layout+ :workspaces))
         (gap (getf +layout+ :gaps))
         (area (policy--area snapshot))
         (output (and area (find (getf area :name) (context snapshot :outputs)
                                 :test #'equal :key (lambda (output) (getf output :name)))))
         (type (getf event :type))
         (command (and (eq type :key) (equal (getf event :owner) "sway") (getf event :command)))
         (motion (rest (assoc command '(("focus-left" -1 0) ("focus-right" 1 0)
                                        ("focus-up" 0 -1) ("focus-down" 0 1))
                              :test #'equal)))
         (active (max 1 (min count (getf state :active))))
         (workspaces (loop for index below count
                           collect (remove-if-not (lambda (id) (member id ids))
                                                  (nth index (getf state :workspaces)))))
         (trees (loop for index below count collect (nth index (getf state :trees))))
         (split (remove-if-not (lambda (entry) (member (car entry) ids)) (getf state :split)))
         (focused (getf state :focus))
         (fullscreen (remove-if-not (lambda (id) (member id ids)) (getf state :fullscreen)))
         (floating (remove-if-not (lambda (entry) (member (car entry) ids)) (getf state :floating)))
         (external (previous-context snapshot :focus))
         (terminal (and (equal command "terminal") (policy--terminal windows)))
         (new nil))
    (labels ((workspace (number) (nth (1- number) workspaces))
             (home (id) (loop for list in workspaces for number from 1
                              when (member id list) return number))
             (boxes (tree)
               (when (and tree area)
                 (sway--boxes tree (+ (getf area :x) gap) (+ (getf area :y) gap)
                              (- (getf area :width) (* 2 gap)) (- (getf area :height) (* 2 gap)) gap)))
             (arrange (number)
               (let* ((keep (remove-if (lambda (id) (or (member id fullscreen) (assoc id floating)))
                                       (workspace number)))
                      (tree (sway--prune (nth (1- number) trees) keep)))
                 (dolist (id keep)
                   (unless (member id (sway--leaves tree))
                     (setf tree
                           (if (null tree)
                               id
                               (let* ((leaves (sway--leaves tree))
                                      (target (if (member focused leaves) focused (car (last leaves))))
                                      (box (assoc target (boxes tree)))
                                      (direction (or (cdr (assoc target split))
                                                     (if (and box (> (fifth box) (fourth box))) :v :h))))
                                 (setf split (remove target split :key #'car))
                                 (sway--insert tree target id direction))))))
                 (setf (nth (1- number) trees) tree)))
             (arrange-all () (loop for number from 1 to count do (arrange number)))
             (switch (number)
               (setf active number focused (car (last (workspace number)))))
             (neighbour (direction) (1+ (mod (+ active -1 direction) count))))
      (when (and (member external ids) (not (eql external focused)))
        (setf focused external active (or (home external) active)))
      (let ((known (loop for list in workspaces append list)))
        (dolist (window windows)
          (let ((id (getf window :id)))
            (unless (member id known)
              (setf (nth (1- active) workspaces) (append (workspace active) (list id)))
              (when (getf window :fullscreen-requested) (push id fullscreen))
              (push id new)))))
      (case type
        (:button
         (when (and (eq (getf event :state) :pressed) (member (getf event :id) (workspace active)))
           (setf focused (getf event :id))))
        ((:metadata :request)
         (let ((id (getf event :id)))
           (when (member id ids)
             (case (getf event :request)
               (:fullscreen
                (setf fullscreen (remove id fullscreen))
                (when (getf event :requested) (push id fullscreen) (setf focused id)))
               (:unfullscreen (setf fullscreen (remove id fullscreen)))
               (:activate (setf active (or (home id) active) focused id)))))))
      (when terminal
        (setf active (or (home terminal) active) focused terminal))
      (arrange-all)
      (let ((current (and (member focused (workspace active)) focused)))
        (cond
          ((null command))
          (motion
           (let ((target (apply #'sway--neighbour (boxes (nth (1- active) trees)) current motion)))
             (when target (setf focused target))))
          ((equal command "workspace-next") (switch (neighbour 1)))
          ((equal command "workspace-previous") (switch (neighbour -1)))
          ((null current))
          ((member command '("move-next" "move-previous") :test #'equal)
           (let ((number (neighbour (if (equal command "move-next") 1 -1))))
             (setf (nth (1- active) workspaces) (remove current (workspace active))
                   (nth (1- number) workspaces) (append (workspace number) (list current)))
             (switch number)))
          ((member command '("swap-previous" "swap-next") :test #'equal)
           (let* ((leaves (sway--leaves (nth (1- active) trees)))
                  (index (position current leaves))
                  (other (and index (+ index (if (equal command "swap-next") 1 -1)))))
             (when (and other (< -1 other (length leaves)))
               (setf (nth (1- active) trees)
                     (sway--swap (nth (1- active) trees) current (nth other leaves))))))
          ((equal command "split-horizontal")
           (setf split (acons current :h (remove current split :key #'car))))
          ((equal command "split-vertical")
           (setf split (acons current :v (remove current split :key #'car))))
          ((equal command "fullscreen")
           (if (member current fullscreen)
               (setf fullscreen (remove current fullscreen))
               (push current fullscreen)))
          ((equal command "floating")
           (cond ((member current fullscreen) (setf fullscreen (remove current fullscreen)))
                 ((assoc current floating) (setf floating (remove current floating :key #'car)))
                 (area (push (cons current (policy--centred area (getf +layout+ :float-ratio)))
                             floating))))))
      (arrange-all)
      (let ((arrived (remove-if-not (lambda (id) (member id (workspace active))) new)))
        (when arrived (setf focused (first arrived))))
      (unless (member focused (workspace active))
        (setf focused (car (last (workspace active)))))
      (let ((effects nil))
        (dolist (id ids)
          (let* ((number (home id))
                 (shown (eql number active))
                 (box (cond ((member id fullscreen)
                             (and output (list (getf output :x) (getf output :y)
                                               (getf output :width) (getf output :height))))
                            ((cdr (assoc id floating)))
                            (t (rest (assoc id (boxes (nth (1- number) trees))))))))
            (push (if box
                      (destructuring-bind (x y width height) box
                        (place id x y (max 1 width) (max 1 height) shown))
                      (if shown (show-window id) (hide-window id)))
                  effects)
            (push (fullscreen id (and (member id fullscreen) t)) effects)))
        (let ((floats (remove-if (lambda (id) (member id fullscreen))
                                 (mapcar #'car (reverse floating)))))
          (dolist (id (append (remove focused floats)
                              (when (member focused floats) (list focused))
                              fullscreen))
            (when (member id (workspace active)) (push (raise-window id) effects))))
        (push (focus focused :raise nil) effects)
        (push (settings :animations nil) effects)
        (dolist (binding +layout-bindings+) (push (apply #'bind-key binding) effects))
        (values (list :active active :workspaces workspaces :trees trees :split split
                      :focus focused :fullscreen fullscreen :floating floating)
                (nreverse effects)
                (when (and (equal command "terminal") (null terminal))
                  (list (apply #'launch (policy--launch "terminal")))))))))
