{
  pkgs,
  flakeInputs,
  ...
}: {
  environment.systemPackages = [
    pkgs.wget
    pkgs.cachix
    pkgs.unzip
    pkgs.lsd
    pkgs.tree
    pkgs.psmisc
    pkgs.lm_sensors
    pkgs.fzf
    pkgs.ripgrep
    flakeInputs.strictix.packages."${pkgs.stdenv.hostPlatform.system}".default
    pkgs.alejandra
    pkgs.statix
    pkgs.deadnix
    pkgs.bluez-tools
    pkgs.rsync
    pkgs.bind
    pkgs.btrbk
    pkgs.fuse3
    pkgs.strace
    pkgs.bc
    pkgs.file
    pkgs.hostname-debian
  ];
}
